#include <stdio.h>
#include <stdlib.h>
#include "codegen.h"

// Prototypes for functions generated by Flex/Bison
extern int yyparse(void);
extern FILE* yyin;

// Prototype declared here to satisfy parser.y requirements cleanly
void emit_runtime_library(void);

void emit_runtime_library(void) {
    printf("\n; ==========================================\n");
    printf("; --- Vircon32 Lua Compiler Runtime Lib ---\n");
    printf("; ==========================================\n");

    // --- Built-in: String Concatenation ---
    // Expects two arguments on the stack: [BP+3]=dest_str_ptr, [BP+2]=src_str_ptr
    printf("\n__builtin_strcat:\n");
    printf("  PUSH BP\n");
    printf("  MOV BP, SP\n");
    printf("  MOV R0, [BP + 3] ; Destination pointer\n");
    printf("  MOV R1, [BP + 2] ; Source pointer\n");
    
    printf("\n__strcat_find_end:\n");
    printf("  MOV R2, [R0]\n");
    printf("  IEQ R2, 0\n");
    printf("  JT R2, __strcat_copy_loop\n");
    printf("  IADD R0, 1       ; Move to next word (Fixed to IADD)\n");
    printf("  JMP __strcat_find_end\n");
    
    printf("\n__strcat_copy_loop:\n");
    printf("  MOV R3, [R1]     ; Load character into intermediate register (Fixed!)\n");
    printf("  MOV [R0], R3     ; Store character into destination address\n");
    printf("  IEQ R3, 0        ; Check for null-terminator\n");
    printf("  JT R3, __strcat_done\n");
    printf("  IADD R0, 1       ; Increment pointers via integer math\n");
    printf("  IADD R1, 1\n");
    printf("  JMP __strcat_copy_loop\n");
    
    printf("\n__strcat_done:\n");
    printf("  MOV SP, BP\n");
    printf("  POP BP\n");
    printf("  RET\n");

    // --- Built-in: Table Assignment (__builtin_table_set) ---
    // Minimal mock runtime stub for key/value tables
    printf("\n__builtin_table_set:\n");
    printf("  PUSH BP\n");
    printf("  MOV BP, SP\n");
    printf("  ; Custom array/hash mapping logic would go here\n");
    printf("  MOV SP, BP\n");
    printf("  POP BP\n");
    printf("  RET\n");

    // --- Built-in: Table Retrieval (__builtin_table_get) ---
    printf("\n__builtin_table_get:\n");
    printf("  PUSH BP\n");
    printf("  MOV BP, SP\n");
    printf("  MOV R0, 0        ; Default fallback return value\n");
    printf("  MOV SP, BP\n");
    printf("  POP BP\n");
    printf("  RET\n");
}

int main(int argc, char** argv) {
    if (argc > 1) {
        FILE* file = fopen(argv[1], "r");
        if (!file) {
            perror("Error opening source file");
            return 1;
        }
        yyin = file;
    } else {
        printf("; Reading from standard input (type your code and press Ctrl+D):\n");
    }

    // Print out basic initialization assembly boilerplate for the emulator
    printf("; --- Program Initialization ---\n");
    printf("  MOV [0], 20000   ; Initialize heap pointer to dynamic RAM region\n");
    printf("  CALL _main       ; Jump directly to user's main structure\n");
    printf("  HLT\n\n");

    // Run the Parser (which loops calls to the Code Generator automatically)
    if (yyparse() != 0) {
        fprintf(stderr, "Compiler Aborted: Parsing error encountered.\n");
        return 1;
    }

    // Append our data sections and utility libraries safely to the end of the file
    emit_string_data_section();
    emit_runtime_library();

    return 0;
}
