#ifndef __V32LUA_H
#define __V32LUA_H

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdbool.h>
#include <string.h>

#include "enums.h"
#include "emit.h"
#include "ast.h"
#include "context.h"
#include "intrinsics.h"
#include "generate.h"
#include "internals.h"
#include "register.h"

#define  VERSION  "20260714-dev"
#define  AUTHOR   "Matthew Haas"
#define  URL      "https://github.com/wedge1020/v32lua"

// Prototypes for functions generated by Flex/Bison
int  yyparse (void);
extern FILE *yyin;

#endif
