#ifndef __V32LUA_H
#define __V32LUA_H

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdbool.h>
#include <string.h>
#include <ctype.h>
#include <math.h>

#include "enums.h"
#include "emit.h"
#include "ast.h"
#include "context.h"
#include "intrinsics.h"
#include "optimize.h"
#include "generate.h"
#include "internals.h"
#include "register.h"

#define  VERSION      "20260721-dev"
#define  AUTHOR       "Matthew Haas"
#define  URL          "https://github.com/wedge1020/v32lua"

#define  V32_CART_PAGE   0x20000000
#define  NAN_VALUE       0x7F800000
#define  BOXED_CATEGORY  0x80000000 // sign bit used for RAM (1) vs ROM (0)
#define  BOXED_TYPE      0x00400000 // quiet-NaN used for TABLE/FUNCTION (0) vs STRING (1)
#define  BOXED_DATA      0xFFC00000 // common bitmask to indicate boxed data
#define  BOXED_FUNCTION  0x7F800000 // bitmask for boxed lua function (ROM)
#define  BOXED_ROMSTRING 0x7FC00000 // bitmank for boxed lua string literal (ROM)
#define  BOXED_TABLE     0xFF800000 // bitmask for boxed lua table (RAM)
#define  BOXED_RAMSTRING 0xFFC00000 // starting at offset 4 (includes nil/false/true)
#define  BOXED_NIL       0xFFC00000
#define  BOXED_FALSE     0xFFC00001
#define  BOXED_BOOLEAN   0xFFC00001 // mathing our way to true/false
#define  BOXED_TRUE      0xFFC00002
#define  BOXED_TOMBSTONE 0xFFC00003 // future feature
#define  BOXED_PAYLOAD   0x003FFFFF

// Prototypes for functions generated by Flex/Bison
int  yyparse (void);
extern FILE *yyin;

#endif
