#line 1 "lexer.c"

#line 3 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 111
#define YY_END_OF_BUFFER 112
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[273] =
    {   0,
        0,    0,    0,    0,  112,  110,    1,    1,  110,  110,
       60,   84,   90,   52,  110,   91,   92,   87,   85,   94,
       86,   99,   89,  105,  105,  100,  101,   58,   93,   59,
       76,   83,  102,   97,   75,   98,   66,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,   95,   53,   96,   54,  110,  110,   11,   12,
       13,    1,   55,    0,  107,    0,   71,   44,    0,  108,
        0,   69,   67,    9,   68,   63,  106,   88,   70,    0,
      105,    0,    0,    0,   21,   50,   56,   36,   57,   51,
      102,    0,   73,   74,   49,  102,  102,  102,   22,  102,

      102,  102,  102,  102,  102,   23,   18,  102,  102,  102,
       32,  102,  102,  102,  102,  102,   45,   37,    0,    0,
        0,    0,   11,    0,   10,    9,    9,    8,    4,    9,
       62,   72,    0,   88,  105,  104,    0,  105,  103,   42,
       47,   48,   43,   46,    0,    0,   41,  102,  102,   31,
      102,  102,   27,  102,   17,  102,  102,  102,   35,   61,
      102,  102,  102,  102,  102,  102,   82,   78,   77,   79,
       80,    0,    9,    9,    8,    4,    4,    9,    0,  106,
        0,    0,   39,   40,   38,  109,  102,  102,  102,   26,
      102,  102,   20,  102,  102,  102,   25,   33,  102,  102,

        0,    0,    0,    0,    0,   81,    9,    9,    9,    4,
        9,    0,    9,  104,  103,  102,  102,   19,  102,   34,
      102,   28,  102,  102,   16,   14,    0,    0,    0,    0,
        0,    0,    9,    9,    9,    4,    0,    4,    0,    3,
      102,  102,   24,  102,   15,   30,   82,   78,   77,   79,
       80,    0,    7,    9,    9,    5,    9,    0,    2,    3,
       64,  102,  102,   81,    6,    9,    2,  102,   29,  102,
       65,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   31,   33,   31,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   35,   34,   34,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   50,   57,   58,   59,   60,   50,   61,   62,
       50,   50,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,   67,   68,   69,    1,    1,    1,    1,    1,
        1,   70,   71,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   72,   73,   74,    1,
       75,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   76,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   77,    1,    1,    1,    1,    1,   78,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   79,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   80,   81,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[82] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    1,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    5,    5,    1,    1,    6,    1,    5,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[288] =
    {   0,
        0,    0,   79,   80,  522,  523,   82,   86,  494,   85,
      523,  523,  493,  492,   82,  523,  523,  491,  490,  523,
       75,   76,   76,   88,   93,  492,  523,   74,  488,   77,
      523,  523,    0,  478,  486,  523,   86,  472,  457,  453,
      454,   54,   86,  453,   78,  452,   79,  449,  460,   83,
      450,  455,  523,  475,  523,  474,   63,  426,    0,  523,
      110,  140,  523,  122,  523,  496,  523,  523,  135,  523,
        0,  523,  523,  144,  523,  134,  133,    0,  523,  141,
      146,  136,  165,  171,  523,  143,  523,  523,  523,  149,
        0,  460,  523,  523,  470,  132,  452,  450,    0,  436,

      449,  440,  434,  436,  430,    0,    0,  445,  435,  427,
        0,  126,  440,  424,  424,  433,  523,  523,  411,  405,
      128,  412,    0,  163,  523,    0,  184,    0,  442,  441,
      523,  523,  202,    0,  205,  200,  177,  208,  457,  523,
      448,  447,  523,  446,  434,  433,  523,  412,  428,    0,
      427,  422,    0,  408,    0,  422,  409,  422,    0,    0,
      417,  401,  406,  414,  409,  405,  376,  375,  374,  373,
      372,  343,  211,  220,    0,    0,  379,  205,  223,  226,
      215,  235,  523,  523,  523,  523,  350,  336,  341,  335,
      319,  304,    0,  310,  320,  303,    0,    0,  307,  313,

      277,  276,  275,  274,  273,  269,  241,  257,  265,  256,
      257,  310,  266,  220,  280,  304,  302,    0,  296,    0,
      292,    0,  280,  284,    0,    0,  266,  260,  259,  249,
      248,  241,  324,  301,  267,  272,  279,  302,  278,    0,
      275,  256,    0,  254,    0,    0,  523,  523,  523,  523,
      523,  237,  523,  262,  303,  523,  258,  201,    0,  523,
        0,  158,  155,  523,  523,  181,  523,  120,    0,  111,
        0,  523,  370,  376,  382,  385,  390,  395,  401,  407,
      413,  419,  423,  427,  433,  439,  445
    } ;

static const flex_int16_t yy_def[288] =
    {   0,
      272,    1,  273,  273,  272,  272,  272,  272,  272,  274,
      272,  272,  272,  272,  275,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  276,  272,  272,  272,  272,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  272,  272,  272,  272,  272,  272,  277,  272,
      272,  272,  272,  274,  272,  274,  272,  272,  275,  272,
      275,  272,  272,  278,  272,  272,  272,  279,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      276,  280,  272,  272,  272,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  272,  272,  272,  272,
      272,  272,  277,  272,  272,  278,  278,  281,  282,  278,
      272,  272,  272,  279,  272,  272,  272,  272,  283,  272,
      272,  272,  272,  272,  280,  280,  272,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  272,  272,  272,  272,
      272,  272,  278,  278,  281,  282,  282,  284,  272,  272,
      272,  272,  272,  272,  272,  272,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      272,  272,  272,  272,  272,  272,  278,  278,  278,  285,
      284,  286,  284,  272,  272,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  272,  272,  272,  272,
      272,  272,  278,  278,  278,  285,  287,  285,  286,  278,
      276,  276,  276,  276,  276,  276,  272,  272,  272,  272,
      272,  272,  272,  278,  278,  272,  278,  287,  282,  272,
      276,  276,  276,  272,  272,  278,  272,  276,  276,  276,
      276,    0,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272
    } ;

static const flex_int16_t yy_nxt[605] =
    {   0,
        6,    7,    8,    7,    7,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   33,   33,   33,   33,   34,   35,   36,   37,   38,
       39,   40,   33,   41,   42,   43,   44,   33,   45,   33,
       33,   46,   33,   47,   48,   33,   49,   33,   50,   51,
       52,   33,   53,   54,   55,   56,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,   57,    6,
       58,   60,   60,   62,   62,   62,   62,   62,   62,   62,
       62,   65,   74,   70,   76,   78,   77,   77,   77,   86,

       87,   75,   79,   89,   90,  100,   80,  101,   81,   81,
       81,   80,   94,   81,   81,   81,   61,   61,   71,   82,
       83,   66,   84,  106,   95,   83,  102,  109,   65,   82,
      113,  107,   83,  110,  119,  120,  124,   83,  121,  114,
      103,   62,   62,   62,   62,  104,   70,  125,  127,   84,
      271,  128,  131,   77,   77,   77,  136,  136,   66,  270,
      132,  135,  135,  135,   80,  133,   81,   81,   81,  140,
      141,   71,  148,  129,  142,  143,  144,  133,   83,  130,
      137,  161,  137,  265,  162,  138,  138,  138,  149,  124,
       83,  139,  139,  139,  169,  170,  171,  138,  138,  138,

      125,  139,  139,  139,  173,  173,  173,  212,  269,  174,
      268,  139,  139,  139,  139,  139,  139,  179,  181,  179,
      136,  136,  180,  180,  180,  135,  135,  135,  138,  138,
      138,  173,  173,  173,  207,  214,  214,   83,  267,  208,
      214,  214,  213,  180,  180,  180,  180,  180,  180,   83,
      209,  209,  209,  209,  209,  215,  215,  215,  237,  212,
      256,  233,  233,  233,  253,  215,  215,  215,  212,  256,
      257,  233,  233,  233,  237,  215,  215,  215,  215,  215,
      215,  233,  233,  233,  233,  233,  233,  234,  234,  234,
      234,  234,  235,  238,  213,  209,  209,  209,  209,  209,

      215,  215,  215,  240,  237,  265,  266,  264,  263,  238,
      215,  215,  215,  262,  261,  260,  258,  252,  251,  250,
      215,  215,  215,  215,  215,  215,  253,  254,  255,  249,
      248,  234,  234,  234,  234,  234,  247,  246,  245,  259,
      244,  243,  242,  241,  233,  233,  233,  239,  232,  231,
      230,  229,  228,  227,  233,  233,  233,  226,  225,  224,
      223,  222,  221,  220,  233,  233,  233,  233,  233,  233,
       59,   59,   59,   59,   59,   59,   64,   64,   64,   64,
       64,   64,   69,  219,   69,   69,   69,   69,   91,   91,
      123,  218,  123,  123,  123,  126,  217,  126,  126,  126,

      126,  134,  216,  134,  134,  134,  134,  145,  145,  145,
      145,  145,  145,  175,  210,  175,  175,  175,  175,  176,
      206,  176,  176,  176,  176,  139,  139,  211,  211,  211,
      211,  211,  211,  236,  236,  236,  236,  236,  236,  212,
      212,  212,  212,  212,  212,  237,  237,  237,  237,  237,
      237,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  146,  185,  184,  183,  182,  178,  177,  172,  168,
      167,  166,  165,  164,  163,  160,  159,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  147,  146,  272,  122,

      118,  117,  116,  115,  112,  111,  108,  105,   99,   98,
       97,   96,   93,   92,   88,   85,   73,   72,   68,   67,
       63,  272,    5,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,

      272,  272,  272,  272
    } ;

static const flex_int16_t yy_chk[605] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    7,    7,    7,    7,    8,    8,    8,
        8,   10,   21,   15,   22,   23,   22,   22,   22,   28,

       28,   21,   23,   30,   30,   42,   24,   42,   24,   24,
       24,   25,   37,   25,   25,   25,    3,    4,   15,   24,
       24,   10,   24,   45,   37,   25,   43,   47,   64,   24,
       50,   45,   24,   47,   57,   57,   61,   25,   57,   50,
       43,   62,   62,   62,   62,   43,   69,   61,   74,   24,
      270,   74,   76,   77,   77,   77,   82,   82,   64,  268,
       76,   80,   80,   80,   81,   77,   81,   81,   81,   86,
       86,   69,   96,   74,   90,   90,   90,   77,   81,   74,
       83,  112,   83,  266,  112,   83,   83,   83,   96,  124,
       81,   84,   84,   84,  121,  121,  121,  137,  137,  137,

      124,   84,   84,   84,  127,  127,  127,  178,  263,  127,
      262,   84,   84,   84,   84,   84,   84,  133,  136,  133,
      136,  136,  133,  133,  133,  135,  135,  135,  138,  138,
      138,  173,  173,  173,  173,  181,  181,  135,  258,  174,
      214,  214,  178,  179,  179,  179,  180,  180,  180,  135,
      174,  174,  174,  174,  174,  182,  182,  182,  210,  211,
      257,  207,  207,  207,  254,  182,  182,  182,  213,  235,
      235,  207,  207,  207,  236,  182,  182,  182,  182,  182,
      182,  207,  207,  207,  207,  207,  207,  208,  208,  208,
      208,  208,  209,  210,  211,  209,  209,  209,  209,  209,

      215,  215,  215,  213,  238,  255,  255,  252,  244,  236,
      215,  215,  215,  242,  241,  239,  237,  232,  231,  230,
      215,  215,  215,  215,  215,  215,  233,  233,  234,  229,
      228,  234,  234,  234,  234,  234,  227,  224,  223,  238,
      221,  219,  217,  216,  233,  233,  233,  212,  206,  205,
      204,  203,  202,  201,  233,  233,  233,  200,  199,  196,
      195,  194,  192,  191,  233,  233,  233,  233,  233,  233,
      273,  273,  273,  273,  273,  273,  274,  274,  274,  274,
      274,  274,  275,  190,  275,  275,  275,  275,  276,  276,
      277,  189,  277,  277,  277,  278,  188,  278,  278,  278,

      278,  279,  187,  279,  279,  279,  279,  280,  280,  280,
      280,  280,  280,  281,  177,  281,  281,  281,  281,  282,
      172,  282,  282,  282,  282,  283,  283,  284,  284,  284,
      284,  284,  284,  285,  285,  285,  285,  285,  285,  286,
      286,  286,  286,  286,  286,  287,  287,  287,  287,  287,
      287,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  158,  157,  156,  154,  152,  151,  149,  148,
      146,  145,  144,  142,  141,  139,  130,  129,  122,  120,
      119,  116,  115,  114,  113,  110,  109,  108,  105,  104,
      103,  102,  101,  100,   98,   97,   95,   92,   66,   58,

       56,   54,   52,   51,   49,   48,   46,   44,   41,   40,
       39,   38,   35,   34,   29,   26,   19,   18,   14,   13,
        9,    5,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,

      272,  272,  272,  272
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[112] =
    {   0,
1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include "v32lua.h"
#include <ctype.h>
#include "parser.h"  // Generated automatically by Bison
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-compare"

static int lex_in_tic80_section = 0;   /* see the TIC-80 asset-data rule */

char *process_string_literal (const char *text, int  len)
{
    // Allocate space. The processed string will never be longer 
    // than the raw string minus the two quotes.
    char *processed  = (char *) malloc (len - 1); 
    if (processed   == NULL) {
        compiler_error (ERR_INTERNAL, -1, "Memory allocation failed while processing string literal\n");
    }
    int   i          = 1; // Start at 1 to skip the opening quote
    int   j          = 0;
    
    while (i < len - 1) { // Stop before the closing quote
        if (text[i] == '\\' && i + 1 < len - 1) {
            i++; // Skip the backslash
            switch (text[i]) {
                case 'n': processed[j++] = '\n'; break;
                case 't': processed[j++] = '\t'; break;
                case 'r': processed[j++] = '\r'; break;
                case '\\': processed[j++] = '\\'; break;
                case '"':  processed[j++] = '"'; break;
                case '\'': processed[j++] = '\''; break;
                case 'x':               // \xHH (Lua 5.2+)
                    if (i + 2 < len - 1 && isxdigit ((unsigned char) text[i + 1]) &&
                        isxdigit ((unsigned char) text[i + 2])) {
                        char hex[3] = { text[i + 1], text[i + 2], 0 };
                        processed[j++] = (char) strtol (hex, NULL, 16);
                        i += 2;
                    } else {
                        processed[j++] = text[i];
                    }
                    break;
                default: 
                    if (isdigit ((unsigned char) text[i])) {   // \ddd, up to 3 digits
                        int v = 0, k = 0;
                        while (k < 3 && i < len - 1 && isdigit ((unsigned char) text[i])) {
                            v = v * 10 + (text[i] - '0'); i++; k++;
                        }
                        i--;
                        processed[j++] = (char) (v & 255);
                        break;
                    }
                    // Unrecognized escape sequence, just keep the character
                    processed[j++] = text[i]; 
                    break;
            }
        } else {
            // Normal character
            processed[j++] = text[i];
        }
        i++;
    }
    processed[j] = '\0'; // Ensure it is null-terminated for the C-side
    if (runtime_req.needs_pico8) pico8_fold_glyphs (processed);
    return (processed);
}

// PICO-8 compound assignment operators (+=, -=, *=, /=, %=). Standard Lua
// has no compound assignment at all -- this is a PICO-8-only extension --
// so all five share this one helper, gated on runtime_req.needs_pico8. By
// the time any of these can be lexed, --#api pico8 (a normal TOKEN_CART_HINT
// reduced earlier in this same single parse pass) has already set that flag,
// PROVIDED the --#api hint appears before the first use in the source --
// the existing convention every cart hint already follows. Outside PICO-8
// mode this fails loudly and immediately rather than falling through to the
// generic "syntax error" the separate '+' '=' tokens would otherwise produce.
//
// The operator itself is carried in yylval.number_val (reusing TOKEN_NUMBER's
// slot in the union) as one of the NodeType enum values (NODE_ADD/NODE_SUB/
// NODE_MUL/NODE_DIV/NODE_MOD) -- parser.y casts it back and feeds it straight
// into the same make_node_binary() every plain '+'/'-'/'*'/'/'/'%' expr
// already uses, so the arithmetic itself needed no new codegen.
// PICO-8-only operator spellings (^^ >>> <<> >>< and their compound forms)
static void require_pico8 (const char *what)
{
    if (!runtime_req.needs_pico8) {
        compiler_error (ERR_LEXICAL, yylineno,
            "'%s' is a PICO-8 operator; add --#api pico8 (or --api pico8) to use it", what);
    }
}

static int long_comment_level;   // the n of --[==[ (n '='s) being skipped
static int compound_assign_token (NodeType op)
{
    if (!runtime_req.needs_pico8) {
        compiler_error (ERR_SYNTAX, yylineno,
            "compound assignment operators (+=, -=, *=, /=, %%=, ..=, \\\\=) are a "
            "PICO-8 extension; add --#api pico8 to use them");
    }
    yylval.number_val = (double) op;
    return TOKEN_COMPOUND_ASSIGN;
}
#line 802 "lexer.c"
/* Add these options to disable the unused functions */
#define YY_NO_INPUT 1

#line 806 "lexer.c"

#define INITIAL 0
#define LONGCOMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 109 "lexer.l"


#line 1025 "lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 273 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 523 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 111 "lexer.l"
{ /* Skip whitespace - Fixed single backslashes */ }
	YY_BREAK
/* 1. Transposed Multiline Comment: --@ ...  */
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 114 "lexer.l"
{
    int len = strlen(yytext);
    // Strip the opening "--@[[" (5 chars) and closing "]]" (2 chars)
    yylval.string_val = strndup(yytext + 5, len - 7);
    return TOKEN_COMMENT_BLOCK;
}
	YY_BREAK
/* 2. Standard Multiline Comment: -- ...  (Silently Skipped) */
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 122 "lexer.l"
{ /* Skip standard multiline comments safely */ }
	YY_BREAK
/* 3. Transposed Single-Line Comment: --@ ... */
case 4:
YY_RULE_SETUP
#line 125 "lexer.l"
{
    // Allocate space and replace "--@" with ";  " to preserve length and add assembly prefix
    char *comment = strdup(yytext);
    int   index   = 0;

    while (comment[index] != '\0')
    {
        if (comment[index] == '-')
        {
            comment[index]  = ';';
        }
        else if (comment[index] == '@')
        {
            break;
        }
        index               = index + 1;
    }
    yylval.string_val = comment;
    return TOKEN_COMMENT_LINE;
}
	YY_BREAK
/* Extract section name between < and > */
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 147 "lexer.l"
{
    char *start = strchr(yytext, '<') + 1;
    char *end = strchr(yytext, '>');
    if (end) *end = '\0';
    yylval.string_val = strdup(start);  // Returns "TILES"
    lex_in_tic80_section = 1;
    return TOKEN_TIC80_SECTION_HEADER;
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 156 "lexer.l"
{
    char *start = strchr(yytext, '<') + 2;  // Skip '<' AND '/'
    char *end = strchr(yytext, '>');
    if (end) *end = '\0';
    yylval.string_val = strdup(start);  // Returns "TILES"
    lex_in_tic80_section = 0;
    return TOKEN_TIC80_SECTION_FOOTER;
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 165 "lexer.l"
{
    // Only INSIDE a TIC-80 -- <SECTION> ... -- </SECTION> block. Outside
    // one, "-- 5:6" / "-- 3:30 timeout" is just a comment -- it used to be
    // returned as asset data anywhere and fail the parse with a syntax error.
    if (!lex_in_tic80_section) {
        /* ordinary comment: skip (yylineno counts the newline itself) */
    } else {
        yylval.string_val = strdup(yytext + 3);  // Skip "-- "
        return TOKEN_TIC80_ASSET_DATA;
    }
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 177 "lexer.l"
{ 
    char *hint = strdup (yytext + 3);
    int len = strlen(hint);
    // Strip trailing \r, \n, or spaces
    while (len > 0 && (hint[len - 1] == '\r' || hint[len - 1] == '\n' || hint[len - 1] == ' ')) {
        hint[--len] = '\0';
    }
    yylval.string_val = hint;
    return (TOKEN_CART_HINT);
}
	YY_BREAK
/* 4. Standard Single-Line Comment: Matches '--' with text, or a bare '--' */
case 9:
YY_RULE_SETUP
#line 189 "lexer.l"
{
    // A comment to the end of the line -- unless it opens a long comment,
    // --[[ ... ]] or --[==[ ... ]==]. The rule above only catches a --[[
    // that runs past the end of its line; on one line (`--[[ x ]] end`)
    // this rule's match is longer and used to swallow the code after the
    // comment, and a --[==[ comment was never recognized at all.
    if (yytext[2] == '[') {
        int n = 0;
        while (yytext[3 + n] == '=') n++;
        if (yytext[3 + n] == '[') {
            long_comment_level = n;
            yyless (4 + n);          // rescan everything after the opener
            BEGIN (LONGCOMMENT);
        }
    }
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 206 "lexer.l"
{
    if ((int) yyleng - 2 == long_comment_level) BEGIN (INITIAL);
    else yyless (1);                 // a ] of another level: skip just it
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 210 "lexer.l"
{ }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 211 "lexer.l"
{ }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 212 "lexer.l"
{ }
	YY_BREAK
case YY_STATE_EOF(LONGCOMMENT):
#line 213 "lexer.l"
{
    compiler_error (ERR_SYNTAX, yylineno, "unfinished long comment (missing ]%.*s])",
                    long_comment_level, "==========================");
    yyterminate ();
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 219 "lexer.l"
{ return TOKEN_WHILE;    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 220 "lexer.l"
{ return TOKEN_REPEAT;   }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 221 "lexer.l"
{ return TOKEN_UNTIL;    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 222 "lexer.l"
{ return TOKEN_FOR;      }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 223 "lexer.l"
{ return TOKEN_IN;       }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 224 "lexer.l"
{ return TOKEN_BREAK;    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 225 "lexer.l"
{ return TOKEN_GOTO;     }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 226 "lexer.l"
{ return TOKEN_DBCOLON;  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 227 "lexer.l"
{ return TOKEN_DO;       }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 228 "lexer.l"
{ return TOKEN_IF;       }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 229 "lexer.l"
{ return TOKEN_ELSEIF;   }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 230 "lexer.l"
{ return TOKEN_THEN;     }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 231 "lexer.l"
{ return TOKEN_ELSE;     }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 232 "lexer.l"
{ return TOKEN_END;      }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 233 "lexer.l"
{ return TOKEN_LOCAL;    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 234 "lexer.l"
{ return TOKEN_FUNCTION; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 235 "lexer.l"
{ return TOKEN_RETURN;   }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 236 "lexer.l"
{ return TOKEN_AND;      }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 237 "lexer.l"
{ return TOKEN_OR;       }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 238 "lexer.l"
{ return TOKEN_TRUE;     }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 239 "lexer.l"
{ return TOKEN_FALSE;    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 240 "lexer.l"
{ return TOKEN_NIL;      }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 242 "lexer.l"
{ return TOKEN_EQ;       }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 243 "lexer.l"
{ return TOKEN_NEQ;      }
	YY_BREAK
/* Bitwise operators (node/bitops.c). Lua 5.3+: & | ~ << >> (and unary
       ~). PICO-8 additionally: ^^ (xor), >>> (logical right shift),
       <<> and >>< (rotate left/right); its >> is arithmetic. The longer
       spellings come first; flex's longest match would pick them anyway. */
case 38:
YY_RULE_SETUP
#line 248 "lexer.l"
{ require_pico8 (">>>="); return compound_assign_token(NODE_LSHR); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 249 "lexer.l"
{ require_pico8 ("<<>="); return compound_assign_token(NODE_ROTL); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 250 "lexer.l"
{ require_pico8 (">><="); return compound_assign_token(NODE_ROTR); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 251 "lexer.l"
{ require_pico8 ("^^=");  return compound_assign_token(NODE_BXOR); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 252 "lexer.l"
{ return compound_assign_token(NODE_SHL); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 253 "lexer.l"
{ return compound_assign_token(NODE_SHR); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 254 "lexer.l"
{ return compound_assign_token(NODE_BAND); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 255 "lexer.l"
{ return compound_assign_token(NODE_BOR); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 256 "lexer.l"
{ require_pico8 (">>>"); return TOKEN_LSHR; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 257 "lexer.l"
{ require_pico8 ("<<>"); return TOKEN_ROTL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 258 "lexer.l"
{ require_pico8 (">><"); return TOKEN_ROTR; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 259 "lexer.l"
{ require_pico8 ("^^");  return TOKEN_BXOR; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 260 "lexer.l"
{ return TOKEN_SHL;      }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 261 "lexer.l"
{ return TOKEN_SHR;      }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 262 "lexer.l"
{ return '&';            }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 263 "lexer.l"
{ return '|';            }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 264 "lexer.l"
{ return TOKEN_BXOR;     }
	YY_BREAK
/* PICO-8 alias for ~= (C-style "not equal"). Real Lua only ever has
       ~=; this is PICO-8-specific sugar, same category as += and the
       then-less if, so it's gated the same way -- checked here rather
       than in parser.y since it produces the exact same TOKEN_NEQ the
       parser already knows how to handle, so no grammar change at all. */
case 55:
YY_RULE_SETUP
#line 270 "lexer.l"
{
                            if (!runtime_req.needs_pico8) {
                                compiler_error (ERR_LEXICAL, yylineno,
                                    "'!=' is a PICO-8 extension (use '~=', or add --#api pico8 to use '!=')");
                            }
                            return TOKEN_NEQ;
                        }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 277 "lexer.l"
{ return TOKEN_LE;       }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 278 "lexer.l"
{ return TOKEN_GE;       }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 279 "lexer.l"
{ return TOKEN_LT;       }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 280 "lexer.l"
{ return TOKEN_GT;       }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 281 "lexer.l"
{ return TOKEN_LEN;      }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 282 "lexer.l"
{ return TOKEN_NOT;      }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 283 "lexer.l"
{ return TOKEN_DOTS;     }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 284 "lexer.l"
{ return TOKEN_CONCAT;   }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 285 "lexer.l"
{ return TOKEN_ASM;      }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 286 "lexer.l"
{ return TOKEN_RAWASM;   }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 287 "lexer.l"
{ return '^'; }
	YY_BREAK
/* PICO-8-only compound assignment (see compound_assign_token() above).
       Listed ahead of the plain '+' '-' '*' '/' '%' rules below, same
       convention as "==" etc. being listed ahead of their single-char
       prefixes -- flex's longest-match rule would pick these correctly
       either way, but grouping the multi-char variant next to its base
       operator matches the rest of this file. */
case 67:
YY_RULE_SETUP
#line 294 "lexer.l"
{ return compound_assign_token(NODE_ADD); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 295 "lexer.l"
{ return compound_assign_token(NODE_SUB); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 296 "lexer.l"
{ return compound_assign_token(NODE_MUL); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 297 "lexer.l"
{ return compound_assign_token(NODE_DIV); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 298 "lexer.l"
{ return compound_assign_token(NODE_MOD); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 299 "lexer.l"
{ return compound_assign_token(NODE_CONCAT); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 300 "lexer.l"
{ return compound_assign_token(NODE_FLOORDIV); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 301 "lexer.l"
{ return compound_assign_token(NODE_POW); }
	YY_BREAK
/* PICO-8 integer division a\b = flr(a/b) */
case 75:
YY_RULE_SETUP
#line 303 "lexer.l"
{
                            if (!runtime_req.needs_pico8) {
                                compiler_error (ERR_LEXICAL, yylineno,
                                    "'\\' (integer division) is a PICO-8 extension; use '//' or add --#api pico8");
                            }
                            return TOKEN_FLOORDIV;
                        }
	YY_BREAK
/* PICO-8 print shorthand: ?expr, ... at the start of a statement */
case 76:
YY_RULE_SETUP
#line 311 "lexer.l"
{
                            if (!runtime_req.needs_pico8) {
                                compiler_error (ERR_LEXICAL, yylineno,
                                    "'?' (print shorthand) is a PICO-8 extension; add --#api pico8");
                            }
                            return TOKEN_PRINT_SHORT;
                        }
	YY_BREAK
/* PICO-8 button glyphs (P8SCII, stored as UTF-8 in .p8 files) are
       predefined globals holding the button numbers. The trailing U+FE0F
       variation selector is optional. */
case 77:
YY_RULE_SETUP
#line 321 "lexer.l"
{ yylval.number_val = 0; return TOKEN_NUMBER; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 322 "lexer.l"
{ yylval.number_val = 1; return TOKEN_NUMBER; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 323 "lexer.l"
{ yylval.number_val = 2; return TOKEN_NUMBER; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 324 "lexer.l"
{ yylval.number_val = 3; return TOKEN_NUMBER; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 325 "lexer.l"
{ yylval.number_val = 4; return TOKEN_NUMBER; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 326 "lexer.l"
{ yylval.number_val = 5; return TOKEN_NUMBER; }
	YY_BREAK
/* PICO-8 peek operators: @a == peek(a), $a == peek4(a); %a == peek2(a)
       is the unary use of '%' (parser.y) */
case 83:
YY_RULE_SETUP
#line 329 "lexer.l"
{ require_pico8 ("@"); return TOKEN_PEEK; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 330 "lexer.l"
{ require_pico8 ("$"); return TOKEN_PEEK4; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 331 "lexer.l"
{ return '+'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 332 "lexer.l"
{ return '-'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 333 "lexer.l"
{ return '*'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 334 "lexer.l"
{
                            /* PICO-8: `//` starts a line comment (PICO-8 has
                               no floor-division operator; `\` divides). Lua:
                               floor division -- give the rest of the line back. */
                            if (!runtime_req.needs_pico8) {
                                yyless (2);
                                return TOKEN_FLOORDIV;
                            }
                        }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 343 "lexer.l"
{ return '/'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 344 "lexer.l"
{ return '%'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 345 "lexer.l"
{ return '('; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 346 "lexer.l"
{ return ')'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 347 "lexer.l"
{ return '='; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 348 "lexer.l"
{ return ','; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 349 "lexer.l"
{ return '{'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 350 "lexer.l"
{ return '}'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 351 "lexer.l"
{ return '['; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 352 "lexer.l"
{ return ']'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 353 "lexer.l"
{ return '.'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 354 "lexer.l"
{ return ':'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 355 "lexer.l"
{ return ';'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 357 "lexer.l"
{ 
                            yylval.string_val  = strdup (yytext); 
                            return (TOKEN_IDENTIFIER); 
                        }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 362 "lexer.l"
{
                            // Hex, with an optional hex fraction (0x1.8 ==
                            // 1.5 -- valid Lua, and PICO-8's 0x0.4 style)
                            char *dot = strchr (yytext, '.');
                            double val = (double) strtoul (yytext, NULL, 16);
                            if (dot != NULL) {
                                double scale = 1.0 / 16.0;
                                for (char *p = dot + 1; *p; p++, scale /= 16.0) {
                                    int d = isdigit ((unsigned char) *p) ? *p - '0'
                                          : (tolower ((unsigned char) *p) - 'a' + 10);
                                    val += d * scale;
                                }
                            }
                            // PICO-8 numbers are signed 16.16: 0x8000..0xffff.ffff
                            // are negative there (0xffff == -1).
                            if (runtime_req.needs_pico8 && val >= 32768.0 && val < 65536.0) {
                                val -= 65536.0;
                            }
                            yylval.number_val = val;
                            return (TOKEN_NUMBER);
                        }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 384 "lexer.l"
{
                            // PICO-8 binary literal (0b1010, 0b0101.1)
                            require_pico8 ("0b");
                            double val = 0.0;
                            char *p = yytext + 2;
                            for (; *p && *p != '.'; p++) val = val * 2 + (*p - '0');
                            if (*p == '.') {
                                double scale = 0.5;
                                for (p++; *p; p++, scale /= 2) val += (*p - '0') * scale;
                            }
                            if (val >= 32768.0 && val < 65536.0) val -= 65536.0;
                            yylval.number_val = val;
                            return (TOKEN_NUMBER);
                        }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 399 "lexer.l"
{
                            /* exponent form (1e-17, 2.5E3) added: TIC-80
                               exports and hand-written tables use it --
                               warm_wheels.lua failed to parse without it */
                            yylval.number_val  = atof (yytext); 
                            return (TOKEN_NUMBER); 
                        }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 407 "lexer.l"
{
                            yylval.number_val  = atof (yytext);
                            return (TOKEN_NUMBER);
                        }
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 412 "lexer.l"
{ 
                            yylval.string_val  = process_string_literal (yytext, yyleng); 
                            return (TOKEN_STRING);
                        }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 417 "lexer.l"
{
                            /* single-quoted strings -- plain Lua, but only
                               "..." used to be accepted */
                            yylval.string_val  = process_string_literal (yytext, yyleng);
                            return (TOKEN_STRING);
                        }
	YY_BREAK
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 424 "lexer.l"
{
                            /* long string [[...]]: no escape processing; a
                               newline right after the opening [[ is dropped,
                               as in Lua */
                            int start = 2, len = yyleng - 4;
                            if (len > 0 && yytext[start] == '\r') { start++; len--; }
                            if (len > 0 && yytext[start] == '\n') { start++; len--; }
                            char *str = (char *) malloc (len + 1);
                            memcpy (str, yytext + start, len);
                            str[len] = '\0';
                            if (runtime_req.needs_pico8) pico8_fold_glyphs (str);
                            yylval.string_val  = str;
                            return (TOKEN_STRING);
                        }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 439 "lexer.l"
{ compiler_error(ERR_LEXICAL, yylineno, "Unexpected character '%s'", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 440 "lexer.l"
ECHO;
	YY_BREAK
#line 1858 "lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 273 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 273 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 272);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 440 "lexer.l"


