//
// v32lua: a Vircon32-targetting lua compiler, written in C. It compiles lua code to
//         Vircon32 assembly.
//
// NOTE: Vircon32 comparison instructions are destructive to destination register, 
//       and overwrite with a 0 (false) or 1 (true), which can then be used with
//       the JT or JF instructions. The comparisons are all 2 operand:
//
//       IEQ R0, R1 ; R0 = (R0 == R1)
//       JT  R0, _label
//
//       Integer comparison instructions are: IEQ, INE, ILT, ILE, IGT, and IGE
//       floating point comparisons are:      FEQ, FNE, FLT, FLE, FGT, and FGE
//
// There are 16 general purpose registers (R0-R15):
//
// R0  - R10: completely available for general use
// R11 - R13: general use, but are also used by MOVS, SETS, and CMPS
// R14 - R15: the stack base pointer and stack pointer register
//
////////////////////////////////////////////////////////////////////////////////////////

#include "v32lua.h"

extern ASTNode *root_node; // Ensure your bison grammar exports the root AST node

// --#include support: populated by main() before yyin is ever opened, via
// expand_includes() (preprocess.c). Empty (NULL/0) for an ordinary
// single-file compile -- compiler_error()/compiler_warning() fall back to
// today's plain "on line N" behavior in that case. See preprocess.h.
LineMapEntry *g_line_map       = NULL;
int           g_line_map_count = 0;

// Prototypes for functions generated by Flex/Bison
extern FILE *yyin;
extern int yydebug;
int  g_verbose_debug;

RuntimeRequirements runtime_req;

static void  print_version (const char *prog_name)
{
    fprintf (stdout, "%s %s\n", prog_name, VERSION);
    fprintf (stdout, "Lua Compiler for Vircon32 (v32lua) by %s\n", AUTHOR);
    fprintf (stdout, "  github: %s\n", URL);
}

static void  print_usage (const char *prog_name)
{
    fprintf (stdout, "Lua Compiler for Vircon32 (%s)\n", prog_name);
    fprintf (stdout, "USAGE: %s [options] file\n", prog_name);
    fprintf (stdout, "Options:\n");
    fprintf (stdout, "  --help       Displays this information\n");
    fprintf (stdout, "  --version    Displays compiler version\n");
    //fprintf (stdout, "  --debugmode  Creates files with results of internal stages\n");
    fprintf (stdout, "  -o <file>    Output file, default name is the same as input\n");
    //fprintf (stdout, "  -b           Compiles the program as a BIOS\n");
    fprintf (stdout, "  -v           Displays additional information (verbose)\n");
    fprintf (stdout, "  -g           Outputs an additional file with debug info\n");
    fprintf (stdout, "  -d           Displays operational debug information\n");
    fprintf (stdout, "  -w           Inhibit all warnings\n");
    //fprintf (stdout, "  -Wall        Enable all warnings\n");
    fprintf (stdout, "\nCartridge options (override the matching --# hint in the source):\n");
    fprintf (stdout, "  --api <name>     API layer: pico8, tic80 or vircon32. Default: detected\n");
    fprintf (stdout, "                   from the file (.p8 -> pico8, .tic -> tic80; a .lua by\n");
    fprintf (stdout, "                   its --#api hint, else TIC()/_draw()/_update() entry points)\n");
    fprintf (stdout, "  --title <text>   Cartridge title. Default: the --#title hint, else the\n");
    fprintf (stdout, "                   cart's own title (TIC-80 '-- title:', PICO-8's first\n");
    fprintf (stdout, "                   comment line) or the file name, prefixed with\n");
    fprintf (stdout, "                   [PICO8] / [TIC80] in those API modes\n");
    fprintf (stdout, "  --p8rate <hz>    PICO-8 sound sample rate: 11025, 22050 (default), 44100\n");
    fprintf (stdout, "\nInput files: .lua, .p8 (PICO-8 cart), .tic (TIC-80 cart, Lua only)\n");
}

// "--opt value" or "--opt=value": returns the value (advancing *i past it),
// or NULL when argv[*i] is not this option.
static const char *option_value (int argc, char **argv, int *i, const char *name)
{
    size_t n = strlen (name);
    if (strncmp (argv[*i], name, n) != 0) return NULL;
    if (argv[*i][n] == '=') return argv[*i] + n + 1;
    if (argv[*i][n] != '\0') return NULL;
    if (*i + 1 >= argc) {
        fprintf (stderr, "Compiler Error: %s needs a value\n", name);
        exit (1);
    }
    return argv[++(*i)];
}

// True if some line of src starts (after indentation) with prefix.
static bool has_line_starting (const char *src, const char *prefix)
{
    size_t n = strlen (prefix);
    for (const char *p = src; p && *p; ) {
        const char *q = p;
        while (*q == ' ' || *q == '\t') q++;
        if (strncmp (q, prefix, n) == 0) return true;
        p = strchr (p, '\n');
        if (p) p++;
    }
    return false;
}

// API auto-detection for a .lua with no --#api / --#p8 hint (and no --api):
// the entry points name the platform. Returns NULL when it isn't clear.
static const char *detect_api_from_source (const char *src)
{
    bool tic   = has_line_starting (src, "function TIC(")    || has_line_starting (src, "function TIC (") ||
                 has_line_starting (src, "TIC=function")      || has_line_starting (src, "TIC = function");
    bool pico8 = has_line_starting (src, "function _draw(")  || has_line_starting (src, "function _update(") ||
                 has_line_starting (src, "function _update60(");
    bool v32   = has_line_starting (src, "function main(")   || has_line_starting (src, "function game_loop(");
    if (tic && !pico8 && !v32) return "tic80";
    if (pico8 && !tic && !v32) return "pico8";
    return NULL;
}

// PICO-8 shows a cart's first comment line as its title: the first line of
// Lua code that isn't blank or a --# hint, if it is a "--" comment.
static void pico8_embedded_title (const char *lua, char *out, size_t out_size)
{
    out[0] = '\0';
    for (const char *p = lua; p && *p; ) {
        const char *eol = strchr (p, '\n');
        size_t len = eol ? (size_t) (eol - p) : strlen (p);
        const char *q = p;
        while (q < p + len && (*q == ' ' || *q == '\t' || *q == '\r')) q++;
        if (q < p + len && strncmp (q, "--#", 3) != 0) {
            if (strncmp (q, "--", 2) == 0 && strncmp (q, "--[[", 4) != 0) {
                q += 2;
                while (q < p + len && (*q == ' ' || *q == '\t')) q++;
                const char *e = p + len;
                while (e > q && (e[-1] == ' ' || e[-1] == '\t' || e[-1] == '\r')) e--;
                size_t n = (size_t) (e - q);
                if (n >= out_size) n = out_size - 1;
                memcpy (out, q, n);
                out[n] = '\0';
            }
            return;
        }
        p = eol ? eol + 1 : NULL;
    }
}

static void log_stage (int  stage_num, const char *stage_name, int  verbose)
{
    if (verbose)
    {
        fprintf (stdout, "stage %d: running %s\n", stage_num, stage_name);
    }
}

int  main (int  argc, char** argv)
{
    if (argc                   <  2)
    {
        print_usage (argv[0]);
        return (1);
    }

    char *input_filename        = NULL;
    char  output_filename[256]  = { 0 };
    int   verbose               = 0;
    int   o_dowarnings          = 1; // display warnings by default
    const char *cli_api         = NULL;
    const char *cli_title       = NULL;
    int         cli_p8rate      = 0;

    g_verbose_debug             = false;

    // --- Command Line Argument Parsing ---
    for (int i = 1; i < argc; i++) {
        const char *val;
        if ((val = option_value(argc, argv, &i, "--api")) != NULL) {
            if      (strcmp(val, "native") == 0 || strcmp(val, "v32") == 0) val = "vircon32";
            if (strcmp(val, "pico8") != 0 && strcmp(val, "tic80") != 0 && strcmp(val, "vircon32") != 0) {
                fprintf(stderr, "Compiler Error: --api must be pico8, tic80 or vircon32 (got '%s')\n", val);
                return 1;
            }
            cli_api = val;
        } else if ((val = option_value(argc, argv, &i, "--title")) != NULL) {
            cli_title = val;
        } else if ((val = option_value(argc, argv, &i, "--p8rate")) != NULL) {
            cli_p8rate = atoi(val);
            if (cli_p8rate != 11025 && cli_p8rate != 22050 && cli_p8rate != 44100) {
                fprintf(stderr, "Compiler Error: --p8rate must be 11025, 22050 or 44100 (got '%s')\n", val);
                return 1;
            }
        } else if (strcmp(argv[i], "-o") == 0 && i + 1 < argc) {
            strncpy(output_filename, argv[++i], sizeof(output_filename) - 1);
        } else if (strcmp(argv[i], "-g") == 0) {
            g_debug_mode = true;
        } else if (strcmp(argv[i], "-w") == 0) {
            o_dowarnings = 0; // disable display of compiler warnings
            g_suppress_warnings = true;
        } else if (strcmp(argv[i], "--verbose") == 0 || strcmp(argv[i], "-v") == 0) {
            verbose = 1;
        } else if (strcmp(argv[i], "--debug") == 0 || strcmp(argv[i], "-d") == 0) {
            g_verbose_debug  = true;
        } else if (strcmp(argv[i], "--version") == 0) {
            print_version(argv[0]);
            return 0;
        } else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return 0;
        } else if (input_filename == NULL) {
            input_filename = argv[i];
        } else {
            fprintf(stderr, "Compiler Error: Unknown or duplicate argument '%s'\n", argv[i]);
            return 1;
        }
    }

    if (input_filename == NULL) {
        fprintf(stderr, "Compiler Error: No input file specified.\n");
        return 1;
    }

    // Default output filename to input_filename.asm if not specified by -o
    if (output_filename[0] == '\0') {
        strncpy(output_filename, input_filename, sizeof(output_filename) - 5);
        char* last_dot = strrchr(output_filename, '.');
        if (last_dot != NULL) {
            strcpy(last_dot, ".asm");
        } else {
            strcat(output_filename, ".asm");
        }
    }

    runtime_req.needs_memory_alloc  = true;  // Heap always needed
    runtime_req.needs_print         = true;
    runtime_req.needs_strings       = true;
    runtime_req.needs_tables        = true;
    runtime_req.needs_iters         = true;
    runtime_req.needs_vircon32      = true;

    tic80_init_default_palette ();

    // --- Command-line cartridge options ---
    // Applied before lexing: PICO-8's extra syntax is only recognised once
    // pico8 mode is on. The in-source hints check the g_cli_*_set flags and
    // leave these values alone.
    if (cli_api != NULL) {
        apply_api_mode (cli_api);
        g_cli_api_set = true;
    }
    if (cli_p8rate != 0) {
        pico8_audio_rate = cli_p8rate;
        g_cli_p8rate_set = true;
    }
    if (cli_title != NULL) {
        strncpy (cart_title, cli_title, sizeof (cart_title) - 1);
        cart_title[sizeof (cart_title) - 1] = '\0';
        cart_title_was_set = true;
        g_cli_title_set    = true;
    }
    bool is_tic_cart = tic80_is_binary_cart_path (input_filename);
    char embedded_tic80_title[128] = { 0 };   // TIC-80 "-- title:" metadata
    char embedded_pico8_title[128] = { 0 };   // PICO-8 first comment line

    g_lua_filename                  = input_filename;
    g_asm_filename                  = output_filename;

    // --- Stage 1: Lexer Setup ---
    log_stage(1, "lexer", verbose);

    // --- Stage 2: Preprocessor (--#include expansion) ---
    // Always runs, even with zero --#include directives present: in that
    // case expand_includes() is a verified byte-for-byte passthrough (see
    // test_preprocess.c) and g_line_map_count comes back 0, which makes
    // compiler_error()/compiler_warning()'s line-number translation a
    // no-op. yyin becomes the expanded buffer rather than input_filename
    // directly -- everything downstream (yylineno, resource-hint ordering,
    // TIC-80 sections) sees one ordinary linear token stream either way.
    log_stage(2, "preprocessor", verbose);
    {
        // A binary TIC-80 cart becomes the text of its .lua project export
        // (code + -- <TILES> ... sections), which the rest of the compiler
        // already understands. See tic80_cart.c.
        char *expanded_source = is_tic_cart
                              ? tic80_cart_to_text (input_filename)
                              : expand_includes (input_filename, &g_line_map, &g_line_map_count);

        // CRLF -> LF (Windows-saved sources): Lua reads a line break inside
        // a long string as "\n", and a stray '\r' in split([[...]], "\n")
        // data silently broke evercore's name lookups.
        {
            char *r = expanded_source, *w = expanded_source;
            for (; *r; r++) {
                if (r[0] == '\r' && r[1] == '\n') continue;
                *w++ = *r;
            }
            *w = '\0';
        }

        // A .p8 cartridge compiles directly: only its __lua__ section is
        // lexed (every other line blanked so line numbers still match the
        // .p8, header replaced by "--#api pico8"), and __gfx__/__gff__/
        // __map__ are parsed as the cart's assets. See pico8_assets.c.
        bool is_p8_cart = pico8_is_cart_text (expanded_source);
        if (is_p8_cart) {
            char *lua_only = pico8_split_cart (expanded_source);
            if (lua_only == NULL) {
                compiler_error (ERR_INTERNAL, -1, "Out of memory splitting .p8 cartridge");
            }
            free (expanded_source);
            expanded_source = lua_only;
        }

        // --- API auto-detection (no --api given) ---
        // .p8 and .tic say what they are. A .lua keeps its own --#api/--#p8
        // hint when it has one; otherwise its entry points decide.
        if (!g_cli_api_set) {
            const char *detected = NULL;
            if (is_p8_cart)       detected = "pico8";
            else if (is_tic_cart) detected = "tic80";
            else if (!strstr (expanded_source, "--#api") && !strstr (expanded_source, "--#p8"))
                detected = detect_api_from_source (expanded_source);
            if (detected != NULL) {
                apply_api_mode (detected);
                if (verbose) {
                    fprintf (stdout, "api: %s (detected)\n", detected);
                }
            }
        }

        // Titles a cart carries itself, used when neither --title nor
        // --#title gives one (decided after parsing, once the API is final).
        snprintf (embedded_tic80_title, sizeof (embedded_tic80_title), "%s",
                  tic80_metatag (expanded_source, "title"));
        pico8_embedded_title (expanded_source, embedded_pico8_title, sizeof (embedded_pico8_title));

        // PICO-8 builtins implemented in Lua (split, tostr, stat, ...):
        // appended when the program uses them. See pico8_prelude.c.
        if (runtime_req.needs_pico8 ||
            (!g_cli_api_set &&
             (strstr (expanded_source, "--#api pico8") ||
              strstr (expanded_source, "--#api \"pico8\"") ||
              strstr (expanded_source, "--#p8")))) {
            expanded_source = pico8_append_prelude (expanded_source);
        }

        yyin = tmpfile ();
        if (yyin == NULL) {
            compiler_error (ERR_INTERNAL, -1,
                "Could not create temporary buffer for --#include expansion");
        }
        fwrite (expanded_source, 1, strlen (expanded_source), yyin);
        rewind (yyin);
        free (expanded_source);
    }

    log_stage(3, "parser", verbose);
    if (yyparse() != 0 || root_node == NULL) {
        fclose(yyin);
        compiler_error(ERR_SYNTAX, -1, "Parsing failed due to syntax errors.");
    }
    fclose(yyin);

    // --- Cartridge title ---
    // --title > --#title > the cart's own title > the file name; the last
    // two get a [PICO8] / [TIC80] prefix in those API modes. Always resolved
    // here, so the XML <rom title> and the __cart_title label agree.
    if (!cart_title_was_set) {
        const char *base   = NULL;
        const char *prefix = "";
        if (runtime_req.needs_tic80) {
            prefix = "[TIC80] ";
            if (embedded_tic80_title[0]) base = embedded_tic80_title;
        } else if (runtime_req.needs_pico8) {
            prefix = "[PICO8] ";
            if (embedded_pico8_title[0]) base = embedded_pico8_title;
        }
        if (base == NULL) base = derive_cart_title_from_filename (input_filename);
        if (strncmp (base, prefix, strlen (prefix)) == 0) prefix = "";
        snprintf (cart_title, sizeof (cart_title), "%s%s", prefix, base);
        cart_title_was_set = true;
    }
    if (verbose) {
        fprintf (stdout, "cart title: \"%s\"\n", cart_title);
    }

    if (runtime_req.needs_tic80)
    {
        process_all_tic80_sections();

        // Always generate + register the texture atlas when TIC-80 support is
        // needed, regardless of whether the source declared any TILES/SPRITES/
        // MAP sections. Even a program with zero custom art still needs
        // texture 0 to exist -- that's where the palette swatch bank
        // (regions 512-527) lives, and pix()/rect()/rectb()/line() all
        // depend on it being present in the cart. tic80_has_assets() answers
        // a narrower question (did the user declare real tile/sprite art)
        // that no longer determines whether textures need to exist at all.
        log_stage(3, "tic80 assets parsing", verbose);

        char base_path[256];
        strncpy(base_path, output_filename, sizeof(base_path));
        char *last_dot = strrchr(base_path, '.');
        if (last_dot) *last_dot = '\0';

        generate_all_tic80_colorkey_textures(base_path);

        // Register all 17 textures in CORRECT order (0-16)
        CARTresource *prev = NULL;
        for (int tex_idx = 0; tex_idx < 17; tex_idx++) {
            char sheet_name[32];
            char sheet_path[512];

            snprintf (sheet_name, sizeof (sheet_name), "tic80_spritesheet_%d", tex_idx);
            snprintf (sheet_path, sizeof (sheet_path), "%s_colorkey_%d", base_path, tex_idx);

            cart_resource_append (&textures_head, &textures_tail,
                                  next_texture_id++, sheet_name, sheet_path);
        }
    }

    if (runtime_req.needs_pico8)
    {
        // Texture 0 ALWAYS exists for a PICO-8 cart: it holds the sprite
        // atlas (from __gfx__, or blank) AND the swatch row that cls()'s
        // siblings rectfill()/circfill()/line()/rect()/pset() draw with.
        // Previously no texture was ever generated or registered, so every
        // spr()/map()/shape primitive drew from a texture that did not exist.
        // Palette index 0 is transparent in the atlas (PICO-8's default palt).
        char base_path[256];
        strncpy (base_path, output_filename, sizeof (base_path) - 1);
        base_path[sizeof (base_path) - 1] = '\0';
        char *last_dot = strrchr (base_path, '.');
        char *last_slash = strrchr (base_path, '/');
        if (last_dot && (!last_slash || last_dot > last_slash)) *last_dot = '\0';

        char sheet_path[300], vtex_path[310];
        snprintf (sheet_path, sizeof (sheet_path), "%s_pico8", base_path);
        snprintf (vtex_path, sizeof (vtex_path), "%s.vtex", sheet_path);
        generate_vtex_from_pico8 (vtex_path, pico8_gfx_pixel, 0);

        if (textures_head != NULL) {
            // hint nodes already baked their ids at parse time
            compiler_error (ERR_SEMANTIC, -1,
                "PICO-8 carts cannot declare --#texture resources: texture 0 "
                "is reserved for the PICO-8 sprite sheet");
        }
        cart_resource_append (&textures_head, &textures_tail,
                              0, "pico8_spritesheet", sheet_path);
        next_texture_id++;
    }

    // --- Stage 4: Semantic Analyzer ---
    log_stage(4, "analyzer", verbose);
    init_global_scope();

    if (runtime_req.needs_tic80)
    {
        // TIC-80 map buffer pointer - must be registered before prepass
        register_global ("TIC80_MAP_BUFFER_PTR");
        register_global ("TIC80_MAP_WIDTH");
        register_global ("TIC80_MAP_HEIGHT");
        register_global ("TIC80_PAUSE_FLAG");
        register_global ("TIC80_COLOR_MULTIPLY");
        register_global ("TIC80_SPRITE_FLAGS_PTR");
        register_global ("TIC80_EXIT_FLAG");
    }


    // ALWAYS allocated (47 words), regardless of runtime_req.needs_vircon32.
    // That flag is not final here: "--#api pico8/tic80" clears it, and the
    // sound/memcard/tilemap intrinsics set it again DURING codegen -- long
    // after this allocation. PICO-8 sfx()/music() did exactly that, and every
    // one of these bases stayed -1, emitting "%define VIRCON32_SFX_CURSOR
    // 0xFFFFFFFF" (a hardware error on first use), while __builtin_pico8_sfx
    // in a cart that never called sfx() referenced an undefined symbol and
    // failed to assemble at all.
    {
        vircon32_btn_prev_state_base      = next_ram_address;
        next_ram_address                  = next_ram_address + 44;
        vircon32_sfx_cursor_base          = next_ram_address;
        next_ram_address                  = next_ram_address + 1;

        // One word each: a 16-bit-relevant bitmask (bit N set = channel N
        // was last assigned a sound by this namespace's .play()). Read and
        // written by __builtin_vircon32_play/_sfx_play (claim on assign)
        // and by music.volume()/sfx.volume()'s no-channel "all my tracked
        // channels" mode. See emit_vircon32_claim_channel_static() and
        // __builtin_vircon32_volume_mask (in vircon32.s) for the two sides
        // of this.
        vircon32_music_channel_mask_base  = next_ram_address;
        next_ram_address                  = next_ram_address + 1;
        vircon32_sfx_channel_mask_base    = next_ram_address;
        next_ram_address                  = next_ram_address + 1;
    }
    
    // Perform full symbol pre-pass before code generation
    register_all_globals_prepass(root_node);

    // Aliases are recorded before codegen so that "play = music.play" at the
    // bottom of a file still governs a play(...) call at the top.
    register_intrinsic_aliases_prepass(root_node);

    // --- Stage 5: Emitter ---
    log_stage(5, "emitter", verbose);

    // 1. Open the file specified by -o
    FILE *asm_file  = fopen (output_filename, "w");
    if (asm_file   == NULL)
    {
        compiler_error (ERR_INTERNAL, -1, "Could not open output file '%s' for writing", output_filename);
    }

    // 2. Point the out() infrastructure to this file
    set_output_stream (asm_file);

    // 3. Run the generator (it will now write to out())
    generate_program (root_node);

    // 4. Safely flush, close, and reset the stream infrastructure
    close_output_stream();

    if ((o_dowarnings == 1) &&
        (w_mainwait   == 1))
    {
        compiler_warning (ERR_SEMANTIC, -1, "main(): no WAIT or ioports.gpu.sync() present");
    }

    // --- Artifact Notification ---
    if (verbose)
    {
        fprintf (stdout, "saving output file\n");
        fprintf (stdout, "saving cart config file\n");
    }
    
    emit_cart_xml (output_filename, verbose);

    if (verbose)
    {
        fprintf (stdout, "compilation successful\n");
    }

    return (0);
}
