//
// v32lua: a Vircon32-targetting lua compiler, written in C. It compiles lua code to
//         Vircon32 assembly.
//
// NOTE: Vircon32 comparison instructions are destructive to destination register, 
//       and overwrite with a 0 (false) or 1 (true), which can then be used with
//       the JT or JF instructions. The comparisons are all 2 operand:
//
//       IEQ R0, R1 ; R0 = (R0 == R1)
//       JT  R0, _label
//
//       Integer comparison instructions are: IEQ, INE, ILT, ILE, IGT, and IGE
//       floating point comparisons are:      FEQ, FNE, FLT, FLE, FGT, and FGE
//
// There are 16 general purpose registers (R0-R15):
//
// R0  - R10: completely available for general use
// R11 - R13: general use, but are also used by MOVS, SETS, and CMPS
// R14 - R15: the stack base pointer and stack pointer register
//
////////////////////////////////////////////////////////////////////////////////////////

#include "v32lua.h"

extern ASTNode *root_node; // Ensure your bison grammar exports the root AST node

// --#include support: populated by main() before yyin is ever opened, via
// expand_includes() (preprocess.c). Empty (NULL/0) for an ordinary
// single-file compile -- compiler_error()/compiler_warning() fall back to
// today's plain "on line N" behavior in that case. See preprocess.h.
LineMapEntry *g_line_map       = NULL;
int           g_line_map_count = 0;

// Prototypes for functions generated by Flex/Bison
extern FILE *yyin;
extern int yydebug;
int  g_verbose_debug;

RuntimeRequirements runtime_req;

static void  print_version (const char *prog_name)
{
    fprintf (stdout, "%s %s\n", prog_name, VERSION);
    fprintf (stdout, "Lua Compiler for Vircon32 (v32lua) by %s\n", AUTHOR);
    fprintf (stdout, "  github: %s\n", URL);
}

static void  print_usage (const char *prog_name)
{
    fprintf (stdout, "Lua Compiler for Vircon32 (%s)\n", prog_name);
    fprintf (stdout, "USAGE: %s [options] file\n", prog_name);
    fprintf (stdout, "Options:\n");
    fprintf (stdout, "  --help       Displays this information\n");
    fprintf (stdout, "  --version    Displays compiler version\n");
    //fprintf (stdout, "  --debugmode  Creates files with results of internal stages\n");
    fprintf (stdout, "  -o <file>    Output file, default name is the same as input\n");
    //fprintf (stdout, "  -b           Compiles the program as a BIOS\n");
    fprintf (stdout, "  -v           Displays additional information (verbose)\n");
    fprintf (stdout, "  -g           Outputs an additional file with debug info\n");
    fprintf (stdout, "  -d           Displays operational debug information\n");
    fprintf (stdout, "  -w           Inhibit all warnings\n");
    //fprintf (stdout, "  -Wall        Enable all warnings\n");
}

static void log_stage (int  stage_num, const char *stage_name, int  verbose)
{
    if (verbose)
    {
        fprintf (stdout, "stage %d: running %s\n", stage_num, stage_name);
    }
}

int  main (int  argc, char** argv)
{
    if (argc                   <  2)
    {
        print_usage (argv[0]);
        return (1);
    }

    char *input_filename        = NULL;
    char  output_filename[256]  = { 0 };
    int   verbose               = 0;
    int   o_dowarnings          = 1; // display warnings by default

    g_verbose_debug             = false;

    // --- Command Line Argument Parsing ---
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-o") == 0 && i + 1 < argc) {
            strncpy(output_filename, argv[++i], sizeof(output_filename) - 1);
        } else if (strcmp(argv[i], "-g") == 0) {
            g_debug_mode = true;
        } else if (strcmp(argv[i], "-w") == 0) {
            o_dowarnings = 0; // disable display of compiler warnings
            g_suppress_warnings = true;
        } else if (strcmp(argv[i], "--verbose") == 0 || strcmp(argv[i], "-v") == 0) {
            verbose = 1;
        } else if (strcmp(argv[i], "--debug") == 0 || strcmp(argv[i], "-d") == 0) {
            g_verbose_debug  = true;
        } else if (strcmp(argv[i], "--version") == 0) {
            print_version(argv[0]);
            return 0;
        } else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return 0;
        } else if (input_filename == NULL) {
            input_filename = argv[i];
        } else {
            fprintf(stderr, "Compiler Error: Unknown or duplicate argument '%s'\n", argv[i]);
            return 1;
        }
    }

    if (input_filename == NULL) {
        fprintf(stderr, "Compiler Error: No input file specified.\n");
        return 1;
    }

    // Default output filename to input_filename.asm if not specified by -o
    if (output_filename[0] == '\0') {
        strncpy(output_filename, input_filename, sizeof(output_filename) - 5);
        char* last_dot = strrchr(output_filename, '.');
        if (last_dot != NULL) {
            strcpy(last_dot, ".asm");
        } else {
            strcat(output_filename, ".asm");
        }
    }

    runtime_req.needs_memory_alloc  = true;  // Heap always needed
    runtime_req.needs_print         = true;
    runtime_req.needs_strings       = true;
    runtime_req.needs_tables        = true;
    runtime_req.needs_iters         = true;
    runtime_req.needs_vircon32      = true;

    tic80_init_default_palette ();

    g_lua_filename                  = input_filename;
    g_asm_filename                  = output_filename;

    // --- Stage 1: Lexer Setup ---
    log_stage(1, "lexer", verbose);

    // --- Stage 2: Preprocessor (--#include expansion) ---
    // Always runs, even with zero --#include directives present: in that
    // case expand_includes() is a verified byte-for-byte passthrough (see
    // test_preprocess.c) and g_line_map_count comes back 0, which makes
    // compiler_error()/compiler_warning()'s line-number translation a
    // no-op. yyin becomes the expanded buffer rather than input_filename
    // directly -- everything downstream (yylineno, resource-hint ordering,
    // TIC-80 sections) sees one ordinary linear token stream either way.
    log_stage(2, "preprocessor", verbose);
    {
        char *expanded_source = expand_includes (input_filename, &g_line_map, &g_line_map_count);

        // CRLF -> LF (Windows-saved sources): Lua reads a line break inside
        // a long string as "\n", and a stray '\r' in split([[...]], "\n")
        // data silently broke evercore's name lookups.
        {
            char *r = expanded_source, *w = expanded_source;
            for (; *r; r++) {
                if (r[0] == '\r' && r[1] == '\n') continue;
                *w++ = *r;
            }
            *w = '\0';
        }

        // A .p8 cartridge compiles directly: only its __lua__ section is
        // lexed (every other line blanked so line numbers still match the
        // .p8, header replaced by "--#api pico8"), and __gfx__/__gff__/
        // __map__ are parsed as the cart's assets. See pico8_assets.c.
        if (pico8_is_cart_text (expanded_source)) {
            char *lua_only = pico8_split_cart (expanded_source);
            if (lua_only == NULL) {
                compiler_error (ERR_INTERNAL, -1, "Out of memory splitting .p8 cartridge");
            }
            free (expanded_source);
            expanded_source = lua_only;
        }

        // PICO-8 builtins implemented in Lua (split, tostr, stat, ...):
        // appended when the program uses them. See pico8_prelude.c.
        if (strstr (expanded_source, "--#api pico8") ||
            strstr (expanded_source, "--#api \"pico8\"") ||
            strstr (expanded_source, "--#p8")) {
            expanded_source = pico8_append_prelude (expanded_source);
        }

        yyin = tmpfile ();
        if (yyin == NULL) {
            compiler_error (ERR_INTERNAL, -1,
                "Could not create temporary buffer for --#include expansion");
        }
        fwrite (expanded_source, 1, strlen (expanded_source), yyin);
        rewind (yyin);
        free (expanded_source);
    }

    log_stage(3, "parser", verbose);
    if (yyparse() != 0 || root_node == NULL) {
        fclose(yyin);
        compiler_error(ERR_SYNTAX, -1, "Parsing failed due to syntax errors.");
    }
    fclose(yyin);

    if (runtime_req.needs_tic80)
    {
        process_all_tic80_sections();

        // Always generate + register the texture atlas when TIC-80 support is
        // needed, regardless of whether the source declared any TILES/SPRITES/
        // MAP sections. Even a program with zero custom art still needs
        // texture 0 to exist -- that's where the palette swatch bank
        // (regions 512-527) lives, and pix()/rect()/rectb()/line() all
        // depend on it being present in the cart. tic80_has_assets() answers
        // a narrower question (did the user declare real tile/sprite art)
        // that no longer determines whether textures need to exist at all.
        log_stage(3, "tic80 assets parsing", verbose);

        char base_path[256];
        strncpy(base_path, output_filename, sizeof(base_path));
        char *last_dot = strrchr(base_path, '.');
        if (last_dot) *last_dot = '\0';

        generate_all_tic80_colorkey_textures(base_path);

        // Register all 17 textures in CORRECT order (0-16)
        CARTresource *prev = NULL;
        for (int tex_idx = 0; tex_idx < 17; tex_idx++) {
            char sheet_name[32];
            char sheet_path[512];

            snprintf (sheet_name, sizeof (sheet_name), "tic80_spritesheet_%d", tex_idx);
            snprintf (sheet_path, sizeof (sheet_path), "%s_colorkey_%d", base_path, tex_idx);

            cart_resource_append (&textures_head, &textures_tail,
                                  next_texture_id++, sheet_name, sheet_path);
        }
    }

    if (runtime_req.needs_pico8)
    {
        // Texture 0 ALWAYS exists for a PICO-8 cart: it holds the sprite
        // atlas (from __gfx__, or blank) AND the swatch row that cls()'s
        // siblings rectfill()/circfill()/line()/rect()/pset() draw with.
        // Previously no texture was ever generated or registered, so every
        // spr()/map()/shape primitive drew from a texture that did not exist.
        // Palette index 0 is transparent in the atlas (PICO-8's default palt).
        char base_path[256];
        strncpy (base_path, output_filename, sizeof (base_path) - 1);
        base_path[sizeof (base_path) - 1] = '\0';
        char *last_dot = strrchr (base_path, '.');
        char *last_slash = strrchr (base_path, '/');
        if (last_dot && (!last_slash || last_dot > last_slash)) *last_dot = '\0';

        char sheet_path[300], vtex_path[310];
        snprintf (sheet_path, sizeof (sheet_path), "%s_pico8", base_path);
        snprintf (vtex_path, sizeof (vtex_path), "%s.vtex", sheet_path);
        generate_vtex_from_pico8 (vtex_path, pico8_gfx_pixel, 0);

        if (textures_head != NULL) {
            // hint nodes already baked their ids at parse time
            compiler_error (ERR_SEMANTIC, -1,
                "PICO-8 carts cannot declare --#texture resources: texture 0 "
                "is reserved for the PICO-8 sprite sheet");
        }
        cart_resource_append (&textures_head, &textures_tail,
                              0, "pico8_spritesheet", sheet_path);
        next_texture_id++;
    }

    // --- Stage 4: Semantic Analyzer ---
    log_stage(4, "analyzer", verbose);
    init_global_scope();

    if (runtime_req.needs_tic80)
    {
        // TIC-80 map buffer pointer - must be registered before prepass
        register_global ("TIC80_MAP_BUFFER_PTR");
        register_global ("TIC80_MAP_WIDTH");
        register_global ("TIC80_MAP_HEIGHT");
        register_global ("TIC80_PAUSE_FLAG");
        register_global ("TIC80_COLOR_MULTIPLY");
        register_global ("TIC80_SPRITE_FLAGS_PTR");
        register_global ("TIC80_EXIT_FLAG");
    }


    // ALWAYS allocated (47 words), regardless of runtime_req.needs_vircon32.
    // That flag is not final here: "--#api pico8/tic80" clears it, and the
    // sound/memcard/tilemap intrinsics set it again DURING codegen -- long
    // after this allocation. PICO-8 sfx()/music() did exactly that, and every
    // one of these bases stayed -1, emitting "%define VIRCON32_SFX_CURSOR
    // 0xFFFFFFFF" (a hardware error on first use), while __builtin_pico8_sfx
    // in a cart that never called sfx() referenced an undefined symbol and
    // failed to assemble at all.
    {
        vircon32_btn_prev_state_base      = next_ram_address;
        next_ram_address                  = next_ram_address + 44;
        vircon32_sfx_cursor_base          = next_ram_address;
        next_ram_address                  = next_ram_address + 1;

        // One word each: a 16-bit-relevant bitmask (bit N set = channel N
        // was last assigned a sound by this namespace's .play()). Read and
        // written by __builtin_vircon32_play/_sfx_play (claim on assign)
        // and by music.volume()/sfx.volume()'s no-channel "all my tracked
        // channels" mode. See emit_vircon32_claim_channel_static() and
        // __builtin_vircon32_volume_mask (in vircon32.s) for the two sides
        // of this.
        vircon32_music_channel_mask_base  = next_ram_address;
        next_ram_address                  = next_ram_address + 1;
        vircon32_sfx_channel_mask_base    = next_ram_address;
        next_ram_address                  = next_ram_address + 1;
    }
    
    // Perform full symbol pre-pass before code generation
    register_all_globals_prepass(root_node);

    // Aliases are recorded before codegen so that "play = music.play" at the
    // bottom of a file still governs a play(...) call at the top.
    register_intrinsic_aliases_prepass(root_node);

    // --- Stage 5: Emitter ---
    log_stage(5, "emitter", verbose);

    // 1. Open the file specified by -o
    FILE *asm_file  = fopen (output_filename, "w");
    if (asm_file   == NULL)
    {
        compiler_error (ERR_INTERNAL, -1, "Could not open output file '%s' for writing", output_filename);
    }

    // 2. Point the out() infrastructure to this file
    set_output_stream (asm_file);

    // 3. Run the generator (it will now write to out())
    generate_program (root_node);

    // 4. Safely flush, close, and reset the stream infrastructure
    close_output_stream();

    if ((o_dowarnings == 1) &&
        (w_mainwait   == 1))
    {
        compiler_warning (ERR_SEMANTIC, -1, "main(): no WAIT or ioports.gpu.sync() present");
    }

    // --- Artifact Notification ---
    if (verbose)
    {
        fprintf (stdout, "saving output file\n");
        fprintf (stdout, "saving cart config file\n");
    }
    
    emit_cart_xml (output_filename, verbose);

    if (verbose)
    {
        fprintf (stdout, "compilation successful\n");
    }

    return (0);
}
