//
// v32lua: a Vircon32-targetting lua compiler, written in C. It compiles lua code to
//         Vircon32 assembly.
//
// NOTE: Vircon32 comparison instructions are destructive to destination register, 
//       and overwrite with a 0 (false) or 1 (true), which can then be used with
//       the JT or JF instructions. The comparisons are all 2 operand:
//
//       IEQ R0, R1 ; R0 = (R0 == R1)
//       JT  R0, _label
//
//       Integer comparison instructions are: IEQ, INE, ILT, ILE, IGT, and IGE
//       floating point comparisons are:      FEQ, FNE, FLT, FLE, FGT, and FGE
//
// There are 16 general purpose registers (R0-R15):
//
// R0  - R10: completely available for general use
// R11 - R13: general use, but are also used by MOVS, SETS, and CMPS
// R14 - R15: the stack base pointer and stack pointer register
//
////////////////////////////////////////////////////////////////////////////////////////

#include "v32lua.h"

// Prototypes for functions generated by Flex/Bison
FILE *yyin;

// Declare the external symbol created by runtime_embed.S
extern const char runtime_asm_start[];

void  emit_runtime_library (void)
{
    emit_asm("\n;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");
    emit_asm(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n");
    emit_asm(";;\n");
    emit_asm(";; Lua assembly support Runtime Library Subroutines\n");
    emit_asm(";;\n");
    emit_asm(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");
    emit_asm(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n");
    emit_asm("\n");

    // Point our cursor to the start of the embedded Vircon32 assembly
    const char* cursor = runtime_asm_start;
    char line[1024];

    // Read until we hit the null terminator we appended in .S
    while (*cursor != '\0')
    {
        int i = 0;
        
        // Extract a single line up to the newline character or buffer capacity
        while (*cursor != '\0' && *cursor != '\n' && i < (int)sizeof(line) - 2)
        {
            line[i++] = *cursor++;
        }
        
        // Preserve the newline character if present
        if (*cursor == '\n')
        {
            line[i++] = *cursor++;
        }
        
        line[i] = '\0';
        
        // Pass the line through your special formatting function
        emit_asm("%s", line);
    }

    emit_asm("\n;;\n");
    emit_asm(";; End of Runtime Library\n");
    emit_asm(";;\n");
    emit_asm(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");
    emit_asm(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n");
}

extern int yydebug;

int main (int  argc, char** argv)
{
    const char *input_filename = argv[1];

    if (argc < 2)
	{
        fprintf(stderr, "Usage: %s <input_file.lua>\n", argv[0]);
        exit (1);
    }

	FILE* file = fopen(argv[1], "r");
	if (!file) {
		perror("Error opening source file");
		return 1;
	}
	yyin = file;

    #if YYDEBUG
    yydebug = 0;
    #endif

    // Run the Parser (which loops calls to the Code Generator automatically)
    if (yyparse() != 0) {
        fprintf(stderr, "Compiler Aborted: Parsing error encountered.\n");
        return 1;
    }

    // 4. Output the Vircon32 cartridge XML file
    emit_cart_xml (input_filename);

    return (0);
}
